### ISSUE TITLE
Element can't securely cache encrypted messages

### ISSUE THREAD

**Issue by heylix** [flathub/im.riot.Riot#123]
In security settings:

>Element can't securely cache encrypted messages locally while running in a web browser. Use Element Desktop for encrypted messages to appear in search results.

People in #element-web:matrix.org told me it's probably because seshat isn't packaged correctly.

**Comment by SISheogorath** [comment]
```
Keytar unexpected error: Error: libsecret-1.so.0: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/Element/resources/app.asar/node_modules/keytar/lib/keytar.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
```

It seems like this is the problem. I'll look into it tonight :)

**Comment by SISheogorath** [comment]
@heylix can you check if #124 fixes your problem? A ready-to-use test-build is provided by flathubbot :) (just make sure to uninstall it afterwards again :wink:)

**Comment by heylix** [comment]
do I just run it with closing Element and starting Element again or do I need to specify the build somewhere?

Because I ran it like this:

```
$ flatpak install --user https://dl.flathub.org/build-repo/23200/im.riot.Riot.flatpakref
The application im.riot.Riot depends on runtimes from:
  https://dl.flathub.org/repo/
Configure this as new remote 'flathub' [Y/n]: 

im.riot.Riot permissions:
    ipc          network              pulseaudio           x11
    devices      file access [1]      dbus access [2]      bus ownership [3]

    [1] xdg-download, xdg-run/keyring
    [2] org.freedesktop.Notifications, org.freedesktop.portal.Fcitx,
        org.kde.StatusNotifierWatcher
    [3] org.kde.StatusNotifierItem-2-1


        ID               Zweig     Op     Remote          Download
 1. [✓] im.riot.Riot     test      i      riot-origin     89,2 MB / 90,5 MB

Installation complete.

$ flatpak run im.riot.Riot
```

and the caching still doesn't work. I tried deleting the cache in the settings but now I have an endless spinner and "connection to home server not possible". Output from above command is:

```
/home/heylix/.var/app/im.riot.Riot/config/Element exists: no
/home/heylix/.var/app/im.riot.Riot/config/Riot exists: yes
Using legacy user data path: /home/heylix/.var/app/im.riot.Riot/config/Riot
(node:2) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Starting auto update with base URL: https://packages.riot.im/desktop/update/
Auto update not supported on this platform
[fake-sandbox: zypak-sandbox] No data could be read (host died?)
[fake-sandbox: zypak-sandbox] Quitting Zygote...
```

**Comment by SISheogorath** [comment]
What distribution and desktop environment are you running, if I may ask?

**Comment by heylix** [comment]
Fedora 32, Xfce 4.14

**Comment by SISheogorath** [comment]
Note: while this is fixed by #124 you need to set up the account again, in best case with deleting the entire profile directory. It's annoying, I know, but I noticed that if I don't set up the account freshly, element caches the knowledge about whether or not this installation can use encrypted search or not.

(This was also the reason why I wasn't able to reproduce the problem.)

**Comment by heylix** [comment]
Ah, right, works now! Thank you!

**Comment by LinAGKar** [comment]
This problem is still around with Element 1.7.4, even after I've reinstalled it and wiped the data.

**Comment by SISheogorath** [comment]
I already noticed a few days ago, that it only works until the first restart of element. it's yet to investigate why. So far, also the upstream maintainers couldn't provide a hint where to investigate further.

**Comment by heylix** [comment]
> This problem is still around with Element 1.7.4, even after I've reinstalled it and wiped the data.

yep, same for me.

**Comment by vchernin** [comment]
I am seemingly able to search through encrypted messages in a room with Element Flatpak 1.7.28. 
Steps:
1. Within an encrypted room click the search button (top right)  
2. Search for a substring of an encrypted message  
3. The searched for message should become "focused" in the chat window  
This correct behaviour persists after Element restarts (I made sure to actually quit not just hide Element).

[This PR](https://github.com/matrix-org/matrix-react-sdk/pull/5806) perhaps solved this issue upstream.

Under Settings > Security & Privacy > Message search and clicking "Manage" it says:

> Message search
Element is securely caching encrypted messages locally for them to appear in search results:
Not currently indexing messages for any room.
Space used: 170 KB
Indexed messages: 45
Indexed rooms: 3 out of 3

I am not sure why it says "Not currently indexing messages for any room" but then says "Indexed messages: 45" just below. Perhaps there's an upstream bug for that.

Can anyone else confirm this behaviour, or clarify if I have missed something?

**Comment by SISheogorath** [comment]
On my end it talked about an invalid passphrase for the search, but finally turned out fine, after resetting it.

A while ago, when this originally came up, I happened to monitor the behaviour that I could only index messages until the next start of the application. This seems to be no longer the case, so I guess this is fine again :)

**Comment by emorrp1** [comment]
> Message search initialisation failed
> Error opening the database: DatabaseError(SqliteFailure(Error { code: NotADatabase, extended_code: 26 }, Some("file is not a database")))

@vchernin Thank you for mentioning the search settings location, where I found the above errors. I thought there had been a regression at some point that caused the flatpak version to not be considered a "Desktop version". But just Settings -> Security and Privacy -> Message search -> Reset -> Reset event store solved the issue, so I probably just ran out of space at some point in the past.

> Message search
> Element is securely caching encrypted messages locally for them to appear in search results:
> Currently indexing: Signal bridge bot
> Space used: 2 MB
> Indexed messages: 1,534
> Indexed rooms: 2 out of 37
