### ISSUE TITLE
[1.1.22] transparent margins on window

### ISSUE THREAD

**Issue by schildbach** [flathub/im.riot.Riot#332]
Since v1.11.22, when I maximize Element Desktop to the left or right half of my screen, I get strange transparent margins on the window. See screenshot.
![Screenshot from 2023-02-03 16-38-07](https://user-images.githubusercontent.com/743306/216644291-14fb66ba-40d4-40f6-b0ef-193ed4c2c4a1.png)
The purple area on the left is actually my desktop background. It can also be another app, if it happens to be there. The same issue is on the bottom of the window.
I'm on Ubuntu 22.04.01, all updates applied.

**Comment by schildbach** [comment]
I just noticed the margin is at the top too (visible in the screenshot even), only it's always white rather than transparent due to the window title background.

**Comment by schildbach** [comment]
The borders actually seem to be window resize handles, according to the form of the mouse pointer when I hover over them. However the upper and lower margin don't resize anything, while the left margin actually seem to move the right window edge rather than the left.

**Comment by t3chguy** [comment]
> I just noticed the margin is at the top too (visible in the screenshot even), only it's always white rather than transparent due to the window title background.

What desktop environment are you using? Because https://flathub.org/apps/details/im.riot.Riot says 

> For GNOME, window decorations are currently missing and you'll have to use keyboard shortcuts instead to resize the window.

**Comment by schildbach** [comment]
> What desktop environment are you using?

Whatever comes with Ubuntu I guess, so it's Gnome-ish. I've not had troubles with window decorations in the past months though, other than the title being white rather than dark despite me having selected dark mode. And I was certainly able to resize the window with the mouse, and still can if I detach it from full screen mode.

By the way, the detached (non-fullscreen) mode is _not_ affected by this issue.

**Comment by schildbach** [comment]
I've got another Flatpak app (the Arduino IDE), and it's **not** affected by this issue.

**Comment by Torbuntu** [comment]
When I snap to the right side in GNOME:
![Screenshot from 2023-02-04 08-07-50](https://user-images.githubusercontent.com/17347324/216772102-9b938184-deb5-4014-8ac8-a7ca7e4d5fdf.png)
If I go to the left the other side does it. 
This is on Fedora Silverblue. I've not seen this with any other applications I'm using (including Arduino IDE ;) )

**Comment by SISheogorath** [comment]
This is probably related to some recent changes by #325 which was supposed to push wayland support.

**Comment by schildbach** [comment]
This issue is still present on the "second" .23 flatpak that was released today.

**Comment by LorbusChris** [comment]
Is this happening under wayland or x11?

**Comment by schildbach** [comment]
> Is this happening under wayland or x11?

It's stock Ubuntu 22.04.2 LTS.

**Comment by develroo** [comment]
Just want to add here. It happens on Version: 1.11.23 on Gnome (43.2) Wayland on Debian Testing. 

It happens both in full screen and half screen modes. 

![Element-Desktop-Flatpak-problem](https://user-images.githubusercontent.com/7777993/222901679-6088db6f-b315-4a2d-931d-56fb4e9c3a6f.png)

![Element-flatpak-problem-2](https://user-images.githubusercontent.com/7777993/222901719-5fe7b95d-697c-409e-b4c0-f8fe5b4a2f2e.png)

**Comment by zevlee** [comment]
This appears to be a Wayland-specific issue. I revoked the Element flatpak's access to the wayland socket and the issue went away for me.

**Comment by LorbusChris** [comment]
This should be fixed by https://github.com/flathub/im.riot.Riot/pull/342

**Comment by schildbach** [comment]
This issue is still present on the 1.11.24 flatpak that was released today.

**Comment by develroo** [comment]
> This issue is still present on the 1.11.24 flatpak that was released today.

Hmm I am on 1.11.24
`
Element	im.riot.Riot	1.11.24	stable	flathub	system`


And I turned off X11 completely,
![Screenshot from 2023-03-08 12-25-54](https://user-images.githubusercontent.com/7777993/223712998-3f08a3b8-b40d-44eb-a36b-f8971839dfb8.png)



and it seems to work for me now.

**Comment by zevlee** [comment]
Like @schildbach I am still experiencing the same problem, even when I follow @develroo's suggestion and disable the X11 socket. The only thing that fixes the issue for me is to disable the wayland socket, as mentioned before.

**Comment by develroo** [comment]
Odd. Well as I said I am on Debian Testing (Gnome 43) and Wayland Maybe it is specific to your distro ?

**Comment by LorbusChris** [comment]
I cannot repro this on Fedora 37 either

**Comment by schildbach** [comment]
This issue is still present on the second 1.11.24 flatpak that was released today.

**Comment by SISheogorath** [comment]
Given we have no stale bot, I think it's enough to mention when it no longer happens.

**Comment by develroo** [comment]
Well that sucks. It upgraded to 1.11.25 and now the transparent margins are back. What is going on here?

**Comment by CR0CKER** [comment]
I'm having the same issue on the latest PopOS with Element version 1.11.29

**Comment by LorbusChris** [comment]
I'm now hitting this too on Fedora 38 in half-screen mode.

**Comment by develroo** [comment]
Yup still a thing on v 1.11.30 on Wayland Gnome 43 came back, dunno why?

**Comment by Torbuntu** [comment]
This is still an issue with the latest updates.
Fedora Silverblue Rawhide (f39)
Element Flatpak 1.11.36

None of the tinkering in flatseal with x11 sockets seemed to make any difference.
